# xset settings
xsetroot -cursor_name left_ptr
xsetroot -solid black
xset b off

# Enables the ctrl+alt+backspace shortcut to kill X
setxkbmap -option terminate:ctrl_alt_bksp

# Remaps some of the keys
xmodmap ~/.xmodmap

# Starts the dropbox script
dropbox start &

# Stop cd drive from ejecting
eject -i 1

# Start IM & IRC
#(pidgin &; sleep 10)
#(xchat &; sleep 10)

# DONT EJECT
eject -i 1

# Starts xmonad
xmonad



