# Add my local ~/bin to path
export PATH=~/bin:/sbin/:~/git/pwntools/bin:$PATH

# App::Nopaste
export NOPASTE_SERVICES='Pastie Codepeek Gist PastebinCom'

# Default editor = vim
export EDITOR=vim
export MPD_HOST=mini

# jdk 1.6
export IDEA_JDK=/usr/lib/jvm/jdk1.6.0_34


#pwntools
export PYTHONPATH=/home/kris/git/pwntools/lib:/home/kris/libsvm-3.16/python:$PYTHONPATH

#JAVA
export PATH=/usr/lib/jvm/java-7-openjdk-amd64/bin/:$PATH

#lesspipe
export LESSOPEN="| /usr/bin/lesspipe %s";
export LESSCLOSE="/usr/bin/lesspipe %s %s";
