#!/bin/sh

connection=`iwconfig 2>/dev/null | egrep "ESSID:[^ ]*" | egrep -v -e "ESSID:off/any" -e "\\x[0-9A-F]{2}" | head -n1`

if [ -z "$connection" ]; then  # Check if an essid was found
  exit 0
fi

interface=`echo $connection | awk '{print $1}'`
essid=`echo $connection | awk -F\" '{print $2}'`

link=`iwconfig $interface | grep -o "Link Quality=[^ ]*" | awk -F= '{print $2}'`
cur_strength=`echo $link | awk -F/ '{print $1}'`
max_strength=`echo $link | awk -F/ '{print $2}'`
ip=`ifconfig $interface | grep -o "inet addr:[^ ]*" | awk -F: '{print $2}'`

echo "$essid: $ip $cur_strength/$max_strength"
